stages:
  - tests
  - stage_deploy

cache:
  paths:
    - env/

before_script:
  - python3 -m venv env
  - source env/bin/activate
  - pip install -r requirements.txt

tests:
  stage: tests
  script:
    - python -m unittest discover -s ./tests/ -t ./tests
  only:
    - merge_requests

flake8:
  stage: tests
  script:
    - flake8 .
  only:
    - merge_requests

stage_deploy:
  stage: stage_deploy
  script:
    - cd $ROOT
    - git checkout --force develop
    - git reset --hard HEAD
    - git pull origin develop
    - ./bin/reload_server.sh
  only:
    - develop
